"""initial_database_seeding

Revision ID: 4d1f984bedec
Revises: 25646d9c224a
Create Date: 2024-05-04 20:58:47.062582

"""
from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision = '4d1f984bedec'
down_revision = '25646d9c224a'
branch_labels = None
depends_on = None


def upgrade():
    # Code generated by ChatGPT

    # Create a temporary 'state' table object to insert data
    state_table = table('state',
                        column('id', Integer),
                        column('name', String))

    # Create a temporary 'city' table object to insert data
    city_table = table('city',
                       column('id', Integer),
                       column('state_id', Integer),
                       column('name', String))


     # List of Australian states and territories
    states = [
        {'id': 1, 'name': 'New South Wales'},
        {'id': 2, 'name': 'Victoria'},
        {'id': 3, 'name': 'Queensland'},
        {'id': 4, 'name': 'Western Australia'},
        {'id': 5, 'name': 'South Australia'},
        {'id': 6, 'name': 'Tasmania'},
        {'id': 7, 'name': 'Australian Capital Territory'},
        {'id': 8, 'name': 'Northern Territory'}
    ]

    # Insert states into the state table
    op.bulk_insert(state_table, states)

    # List of cities by state
    cities = [
        {'id': 1, 'name': 'Sydney', 'state_id': 1},
        {'id': 2, 'name': 'Newcastle', 'state_id': 1},
        {'id': 3, 'name': 'Wollongong', 'state_id': 1},
        {'id': 4, 'name': 'Melbourne', 'state_id': 2},
        {'id': 5, 'name': 'Geelong', 'state_id': 2},
        {'id': 6, 'name': 'Ballarat', 'state_id': 2},
        {'id': 7, 'name': 'Brisbane', 'state_id': 3},
        {'id': 8, 'name': 'Gold Coast', 'state_id': 3},
        {'id': 9, 'name': 'Cairns', 'state_id': 3},
        {'id': 10, 'name': 'Perth', 'state_id': 4},
        {'id': 11, 'name': 'Fremantle', 'state_id': 4},
        {'id': 12, 'name': 'Bunbury', 'state_id': 4},
        {'id': 13, 'name': 'Adelaide', 'state_id': 5},
        {'id': 14, 'name': 'Mount Gambier', 'state_id': 5},
        {'id': 15, 'name': 'Port Augusta', 'state_id': 5},
        {'id': 16, 'name': 'Hobart', 'state_id': 6},
        {'id': 17, 'name': 'Launceston', 'state_id': 6},
        {'id': 18, 'name': 'Devonport', 'state_id': 6},
        {'id': 19, 'name': 'Canberra', 'state_id': 7},
        {'id': 20, 'name': 'Darwin', 'state_id': 8},
        {'id': 21, 'name': 'Alice Springs', 'state_id': 8},
        {'id': 22, 'name': 'Palmerston', 'state_id': 8}
    ]

    # Insert cities into the city table
    op.bulk_insert(city_table, cities)

    category_table = table('category',
                    column('id', Integer),
                    column('name', String))
    
    categories = [
        {'id': 1, 'name': 'Other'},
        {'id': 2, 'name': 'Electronics'},
        {'id': 3, 'name': 'Apparel'},
        {'id': 4, 'name': 'Home & Garden'},
        {'id': 5, 'name': 'Toys & Games'},
        {'id': 6, 'name': 'Books'},
        {'id': 7, 'name': 'Health & Beauty'},
        {'id': 8, 'name': 'Sports & Outdoors'}
    ]

    op.bulk_insert(category_table, categories)


def downgrade():
    # Code generated by ChatGPT
    op.execute("DELETE FROM city WHERE id BETWEEN 1 AND 22")
    op.execute("DELETE FROM state WHERE id BETWEEN 1 AND 8")
    op.execute("DELETE FROM category WHERE id BETWEEN 1 AND 8")
