"""Missing field

Revision ID: 68978d20c5a7
Revises: fcf9db2f6a62
Create Date: 2024-05-19 17:44:14.853325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68978d20c5a7'
down_revision = 'fcf9db2f6a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('delete_time')

    # ### end Alembic commands ###
