"""update_item_requests_missing_fields

Revision ID: 8269e2519e33
Revises: 8787cb7c7086
Create Date: 2024-05-11 19:05:55.697445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8269e2519e33'
down_revision = '8787cb7c7086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_address_user_id'), ['user_id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_city_name'), ['name'])

    with op.batch_alter_table('item_auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_bid_price', sa.Float(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_bid_id')

    with op.batch_alter_table('item_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sender_message', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiver_message', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))
        # No constraint explicitly made
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_item_request_receiver_id_user'), 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_item_request_sender_id_user'), 'user', ['sender_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('message')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_state_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_state_name'), type_='unique')

    with op.batch_alter_table('item_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_item_request_sender_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_item_request_receiver_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('accepted')
        batch_op.drop_column('receiver_message')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_message')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('item_auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_bid_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'bid', ['current_bid_id'], ['id'])
        batch_op.drop_column('current_bid_price')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_city_name'), type_='unique')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_address_user_id'), type_='unique')

    # ### end Alembic commands ###
