"""new_model_item_request

Revision ID: 8787cb7c7086
Revises: 97ef640252d5
Create Date: 2024-05-10 23:16:06.640153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8787cb7c7086'
down_revision = '97ef640252d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('offer_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_request')
    # ### end Alembic commands ###
