"""some_new_constraint_for_user_item_saved

Revision ID: 97ef640252d5
Revises: 42e2acc932d1
Create Date: 2024-05-06 23:05:54.459580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ef640252d5'
down_revision = '42e2acc932d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item_saved', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('unique_user_item_saved_user_id_item_id', ['user_id', 'item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item_saved', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_item_saved_user_id_item_id', type_='unique')
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
