"""update_item_requests_missing_fields

Revision ID: bd69a75149d5
Revises: 8787cb7c7086
Create Date: 2024-05-11 18:04:09.118420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd69a75149d5'
down_revision = '8787cb7c7086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=False))

    with op.batch_alter_table('item_auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_bid_price', sa.Float(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_bid_id')

    with op.batch_alter_table('item_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('accepted')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('item_auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_bid_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'bid', ['current_bid_id'], ['id'])
        batch_op.drop_column('current_bid_price')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('sold')
        batch_op.drop_column('deleted_time')

    # ### end Alembic commands ###
