"""update_item_sold_to_sold_time

Revision ID: fcf9db2f6a62
Revises: 8269e2519e33
Create Date: 2024-05-11 21:57:09.136498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf9db2f6a62'
down_revision = '8269e2519e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('sold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False))
        batch_op.drop_column('sold_time')

    # ### end Alembic commands ###
